import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const srcDir = path.join(__dirname, '../src');
const v2Dir = path.join(srcDir, 'styles/v2');
const distDir = path.join(v2Dir, 'dist');
const outputFile = path.join(distDir, 'v2-bundle.css');

// Ordered list of modules for predictable CSS cascade
const modulePaths = [
  path.join(v2Dir, 'tokens.css'),
  path.join(v2Dir, 'base.css'),
  path.join(v2Dir, 'layout.css'),
  path.join(v2Dir, 'hero-parallax.css'),
  path.join(v2Dir, 'header.css'),
  path.join(v2Dir, 'navbar.css'),
  path.join(v2Dir, 'cards.css'),
  path.join(srcDir, 'desktop/styles/cards-desktop.css'),
  path.join(srcDir, 'mobile/styles/cards-mobile.css'),
  path.join(v2Dir, 'timeline.css'),
  path.join(v2Dir, 'modals.css'),
  path.join(v2Dir, 'mobile-nav.css'),
  path.join(v2Dir, 'event-feed.css'),
  path.join(v2Dir, 'events.css'),
  path.join(srcDir, 'desktop/styles/events-desktop.css'),
  path.join(srcDir, 'mobile/styles/events-mobile.css'),
];

function buildV2() {
  console.log('=== Building SeasonForge CSS v2 Bundle ===');

  if (!fs.existsSync(v2Dir)) {
    console.error(`Source directory not found: ${v2Dir}`);
    process.exit(1);
  }

  if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir, { recursive: true });
  }

  let combinedCss = `/* SeasonForge CSS v2 Bundle — AUTO-GENERATED BY scripts/build-v2.js */\n/* Generated on: ${new Date().toISOString()} */\n\n`;
  let processedCount = 0;

  for (const filePath of modulePaths) {
    const fileName = path.basename(filePath);
    if (fs.existsSync(filePath)) {
      const content = fs.readFileSync(filePath, 'utf-8');
      combinedCss += `/* --- Module: ${fileName} (${path.relative(srcDir, filePath)}) --- */\n${content}\n\n`;
      processedCount++;
      console.log(`  [+] Included: ${path.relative(srcDir, filePath)}`);
    } else {
      console.warn(`  [-] Missing module: ${filePath}`);
    }
  }

  fs.writeFileSync(outputFile, combinedCss, 'utf-8');
  console.log(`\nSuccessfully bundled ${processedCount} module(s) into: ${outputFile}`);
}

export { buildV2 };

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  buildV2();
}
