import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { getIconSvg } from '../src/utils/icons.js';

import { initDomMock } from './builder/domMock.js';
import { validatePages } from './builder/pageValidator.js';
import { buildV2 } from './build-v2.js';

// 1. Mock browser globals for Node.js SSG execution
initDomMock();

// 2. Import frontend components dynamically after mocks are set
const { render: renderGameCard } = await import('../src/components/GameCard.js');
const { render: renderProgressBar } = await import('../src/components/ProgressBar.js');
const { getVal } = await import('../src/i18n/index.js');
const { getProgressPercent, calculateCountdown } = await import('../src/utils/countdown.js');
const { escapeAttr, escapeHtml } = await import('../src/utils/helpers.js');
const { SeoGenerator } = await import('../src/utils/SeoGenerator.js');
const { formatLastUpdated } = await import('../src/utils/date.js');
const { renderEventCard } = await import('../src/components/EventCard.js');
const { renderEventsTimeline } = await import('../src/components/EventsTimeline.js');
const { render: renderNavbar } = await import('../src/components/Navbar.js');

function escapeJsonForScript(str) {
  return String(str || '')
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

function slugify(str) {
  return String(str || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/[\s_]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const dataDir = path.join(__dirname, '../data');
const templatePath = path.join(__dirname, '../src/templates/game.html');
const seasonTemplatePath = path.join(__dirname, '../src/templates/season.html');

async function build() {
  console.log('=== Starting Static Site Generation (SSG) ===');

  // Build CSS v2 bundle first to ensure latest styles
  buildV2();

  const BASE_URL = process.env.BASE_URL || 'https://seasonforge.online';
  const generatedSeasonUrls = [];

  const seasonsPath = path.join(dataDir, 'seasons.json');
  if (!fs.existsSync(seasonsPath)) {
    console.error('Database file seasons.json not found. Run update-seasons first.');
    process.exit(1);
  }

  if (!fs.existsSync(templatePath)) {
    console.error('Layout template file src/templates/game.html not found.');
    process.exit(1);
  }

  const database = JSON.parse(fs.readFileSync(seasonsPath, 'utf-8'));
  const games = database.games || [];
  let template = fs.readFileSync(templatePath, 'utf-8');

  // Generate fallback-seasons.js — always in sync with current seasons.json
  const fallbackPath = path.join(__dirname, '../src/data/fallback-seasons.js');
  const fallbackDir = path.dirname(fallbackPath);
  if (!fs.existsSync(fallbackDir)) fs.mkdirSync(fallbackDir, { recursive: true });
  fs.writeFileSync(
    fallbackPath,
    `// AUTO-GENERATED by scripts/build.js — do not edit manually.\n// Regenerated on every build to stay in sync with data/seasons.json.\nexport const FALLBACK_SEASONS_DATA = ${JSON.stringify(database, null, 2)};\n`,
    'utf-8'
  );
  console.log('[SSG] fallback-seasons.js generated from current seasons.json.');


  // Always refresh lastCheckedAt on build to prevent stale timestamps
  const nowIso = new Date().toISOString();
  database.lastCheckedAt = nowIso;
  fs.writeFileSync(seasonsPath, JSON.stringify(database, null, 2), 'utf-8');

  const lastCheckedAt = database.lastCheckedAt;
  const updateTimes = games.map(g => new Date(g.status?.updatedAt).getTime()).filter(ts => !Number.isNaN(ts));
  if (Array.isArray(database.changelog)) {
    database.changelog.forEach(c => {
      const ts = new Date(c.timestamp).getTime();
      if (!Number.isNaN(ts)) updateTimes.push(ts);
    });
  }
  const latestUpdateTime = updateTimes.length > 0 ? Math.max(...updateTimes) : Date.now();
  
  const lastCheckedFormatted = formatLastUpdated(lastCheckedAt);
  const lastUpdatedFormatted = formatLastUpdated(latestUpdateTime);

  // 0. Update root index.html timestamps
  const rootIndexHtmlPath = path.join(__dirname, '../index.html');
  if (fs.existsSync(rootIndexHtmlPath)) {
    let indexContent = fs.readFileSync(rootIndexHtmlPath, 'utf-8');
    indexContent = indexContent
      .replace(/<strong id="last-checked-time">[\s\S]*?<\/strong>/g, `<strong id="last-checked-time">${lastCheckedFormatted}</strong>`)
      .replace(/<strong id="last-updated-time">[\s\S]*?<\/strong>/g, `<strong id="last-updated-time">${lastUpdatedFormatted}</strong>`);
    fs.writeFileSync(rootIndexHtmlPath, indexContent, 'utf-8');
  }

  template = template
    .replace(/<strong id="last-checked-time">[\s\S]*?<\/strong>/g, `<strong id="last-checked-time">${lastCheckedFormatted}</strong>`)
    .replace(/<strong id="last-updated-time">[\s\S]*?<\/strong>/g, `<strong id="last-updated-time">${lastUpdatedFormatted}</strong>`);

  for (const game of games) {
    const gameId = game.id;
    const gameName = getVal(game.name, 'en'); // Pre-render name in English
    const gameColor = game.color || '#4b5563';

    console.log(`[SSG] Compiling page for: ${gameName} (${gameId})...`);

    // 1. Calculate and pre-render components
    const progress = getProgressPercent(game);
    const progressBarHtml = renderProgressBar(progress);
    const countdown = calculateCountdown(game.nextSeason?.startDate);
    const cardHtml = renderGameCard(game, { 
      countdown, 
      progressBar: progressBarHtml,
      isDetailPage: true 
    });

    // 2. Load "About Seasons" content file if it exists
    const contentPath = path.join(__dirname, `../content/${gameId}.json`);
    let aboutHtml = '';
    let aboutJson = '{}';
    if (fs.existsSync(contentPath)) {
      try {
        const contentData = JSON.parse(fs.readFileSync(contentPath, 'utf-8'));
        if (contentData.about) {
          aboutHtml = contentData.about.en || '';
          aboutJson = JSON.stringify(contentData.about);
        }
      } catch (err) {
        console.error(`[SSG] Error reading content for ${gameId}:`, err.message);
      }
    }

    // 2b. Load "History/Timeline" data file if it exists
    const historyPath = path.join(__dirname, `../data/history/${gameId}.json`);
    let timelineHtml = '';
    let timelineJson = '[]';
    if (fs.existsSync(historyPath)) {
      try {
        const historyData = JSON.parse(fs.readFileSync(historyPath, 'utf-8'));
        timelineJson = JSON.stringify(historyData);

        // Clean up stale season subdirectories for this game to prevent orphaned old pages
        const targetDir = path.join(__dirname, `../games/${gameId}`);
        if (fs.existsSync(targetDir)) {
          const existingEntries = fs.readdirSync(targetDir);
          for (const entry of existingEntries) {
            const fullPath = path.join(targetDir, entry);
            if (entry !== 'index.html' && fs.statSync(fullPath).isDirectory()) {
              fs.rmSync(fullPath, { recursive: true, force: true });
            }
          }
        }

        let seasonTemplate = fs.existsSync(seasonTemplatePath) ? fs.readFileSync(seasonTemplatePath, 'utf-8') : '';
        seasonTemplate = seasonTemplate
          .replace(/<strong id="last-checked-time">[\s\S]*?<\/strong>/g, `<strong id="last-checked-time">${lastCheckedFormatted}</strong>`)
          .replace(/<strong id="last-updated-time">[\s\S]*?<\/strong>/g, `<strong id="last-updated-time">${lastUpdatedFormatted}</strong>`);

        const rows = [];

        for (let i = 0; i < historyData.length; i++) {
          const item = historyData[i];
          const seasonName = item.season?.en || item.season?.ru || 'Season';
          const seasonSlug = item.slug || slugify(seasonName) || `season-${i + 1}`;
          const seasonUrl = `./${seasonSlug}/`;
          generatedSeasonUrls.push(`${BASE_URL}/games/${gameId}/${seasonSlug}/`);

          const start = item.startDate;
          const end = item.endDate;
          
          let durationStr = '—';
          if (start) {
            const startDateObj = new Date(start);
            if (end) {
              const endDateObj = new Date(end);
              const diffDays = Math.round((endDateObj - startDateObj) / (1000 * 60 * 60 * 24));
              durationStr = `${diffDays} days`;
            } else {
              durationStr = 'Ongoing';
            }
          }
          
          const formattedStart = start ? new Intl.DateTimeFormat('en-US', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(start)) : 'TBA';
          const formattedEnd = end ? new Intl.DateTimeFormat('en-US', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(end)) : (start ? 'Ongoing' : 'TBA');
          const svgExternalIcon = `<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" style="opacity: 0.85; margin-left: 2px;"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path><polyline points="15 3 21 3 21 9"></polyline><line x1="10" y1="14" x2="21" y2="3"></line></svg>`;
          const linkHtml = item.sourceUrl 
            ? `<a href="${escapeAttr(item.sourceUrl)}" target="_blank" rel="noopener noreferrer" class="history-table__link"><span class="lbl-official-source-text">Official Source</span>${svgExternalIcon}</a>` 
            : '—';
            
          rows.push(`
            <tr style="border-bottom: 1px solid #1f2937;">
              <td style="padding: 0.75rem 0.5rem; font-weight: 600;">
                <a href="${escapeAttr(seasonUrl)}" class="history-table__season-link" style="color: #818cf8; text-decoration: none; transition: color 0.2s;">${escapeHtml(seasonName)} →</a>
              </td>
              <td style="padding: 0.75rem 0.5rem;" data-label="Start">${formattedStart}</td>
              <td style="padding: 0.75rem 0.5rem;" data-label="End">${formattedEnd}</td>
              <td style="padding: 0.75rem 0.5rem;" data-label="Duration">${durationStr}</td>
              <td style="padding: 0.75rem 0.5rem;">${linkHtml}</td>
            </tr>
          `);

          // Build individual SSG Season Page if seasonTemplate exists
          if (seasonTemplate) {
            const seasonTargetDir = path.join(__dirname, `../games/${gameId}/${seasonSlug}`);
            if (!fs.existsSync(seasonTargetDir)) {
              fs.mkdirSync(seasonTargetDir, { recursive: true });
            }

            const prevItem = historyData[i + 1];
            const nextItem = historyData[i - 1];

            const prevSlug = prevItem ? (prevItem.slug || slugify(prevItem.season?.en || '')) : null;
            const nextSlug = nextItem ? (nextItem.slug || slugify(nextItem.season?.en || '')) : null;

            const prevHtml = prevItem && prevSlug 
              ? `<a href="../${prevSlug}/" class="season-nav-btn">← ${escapeHtml(prevItem.season?.en || 'Previous Season')}</a>` 
              : '';

            const nextHtml = nextItem && nextSlug 
              ? `<a href="../${nextSlug}/" class="season-nav-btn">${escapeHtml(nextItem.season?.en || 'Next Season')} →</a>` 
              : '';

            let statusBadge = '<span class="status-badge status-badge--ended">Ended</span>';
            const now = new Date();
            if (start && new Date(start) > now) {
              statusBadge = '<span class="status-badge status-badge--upcoming">Upcoming</span>';
            } else if (!end && start) {
              statusBadge = '<span class="status-badge status-badge--active">Active Season</span>';
            } else if (!start) {
              statusBadge = '<span class="status-badge status-badge--upcoming">Upcoming</span>';
            }

            const seasonDesc = item.summary?.en || `${gameName} ${seasonName}: start date, end date, duration and full season timeline.`;
            const seasonCanonicalUrl = `${BASE_URL}/games/${gameId}/${seasonSlug}/`;
            const todayISO = now.toISOString().split('T')[0];

            // Schema.org for Season Page
            const seasonSchema = {
              "@context": "https://schema.org",
              "@graph": [
                {
                  "@type": "BreadcrumbList",
                  "itemListElement": [
                    { "@type": "ListItem", "position": 1, "name": "Home", "item": BASE_URL },
                    { "@type": "ListItem", "position": 2, "name": gameName, "item": `${BASE_URL}/games/${gameId}/` },
                    { "@type": "ListItem", "position": 3, "name": seasonName, "item": seasonCanonicalUrl }
                  ]
                },
                {
                  "@type": "Event",
                  "name": `${gameName} - ${seasonName}`,
                  "startDate": start || todayISO,
                  ...(end ? { "endDate": end } : {}),
                  "dateModified": todayISO,
                  "eventAttendanceMode": "https://schema.org/OnlineEventAttendanceMode",
                  "eventStatus": "https://schema.org/EventScheduled",
                  "location": {
                    "@type": "VirtualLocation",
                    "url": seasonCanonicalUrl
                  },
                  "description": seasonDesc,
                  "organizer": {
                    "@type": "Organization",
                    "name": game.developer || "Developer"
                  }
                },
                {
                  "@type": "FAQPage",
                  "mainEntity": [
                    {
                      "@type": "Question",
                      "name": `When did ${seasonName} start?`,
                      "acceptedAnswer": {
                        "@type": "Answer",
                        "text": `${seasonName} for ${gameName} started on ${formattedStart}.`
                      }
                    },
                    {
                      "@type": "Question",
                      "name": `How long is ${seasonName}?`,
                      "acceptedAnswer": {
                        "@type": "Answer",
                        "text": `The total duration of ${seasonName} is ${durationStr}.`
                      }
                    }
                  ]
                }
              ]
            };

            let faqHtml = `
              <div style="display: flex; flex-direction: column; gap: 1rem; color: #d1d5db; font-size: 0.95rem;">
                <div style="background: rgba(0,0,0,0.2); padding: 1rem; border-radius: 0.5rem;">
                  <strong id="faq-q1" style="display: block; color: #f3f4f6; font-size: 1rem; margin-bottom: 0.35rem;">When did ${escapeHtml(seasonName)} start?</strong>
                  <p id="faq-a1" style="margin: 0; color: #9ca3af;">${escapeHtml(seasonName)} for ${escapeHtml(gameName)} started on <strong>${formattedStart}</strong>.</p>
                </div>
                <div style="background: rgba(0,0,0,0.2); padding: 1rem; border-radius: 0.5rem;">
                  <strong id="faq-q2" style="display: block; color: #f3f4f6; font-size: 1rem; margin-bottom: 0.35rem;">How long does ${escapeHtml(seasonName)} last?</strong>
                  <p id="faq-a2" style="margin: 0; color: #9ca3af;">The duration for ${escapeHtml(seasonName)} is <strong>${durationStr}</strong> (End date: ${formattedEnd}).</p>
                </div>
              </div>
            `;

            let extraDetailsHtml = '';
            const mechanicsListEn = item.mechanics?.en || [];
            const rewardsListEn = item.rewards?.en || [];

            if (mechanicsListEn.length > 0 || rewardsListEn.length > 0) {
              const mechanicsLis = mechanicsListEn.map(m => `<li style="margin-bottom: 0.5rem; color: #d1d5db; line-height: 1.5;">${escapeHtml(m)}</li>`).join('');
              const rewardsLis = rewardsListEn.map(r => `<li style="margin-bottom: 0.5rem; color: #d1d5db; line-height: 1.5;">${escapeHtml(r)}</li>`).join('');

              extraDetailsHtml = `
                <div class="season-extra-details" style="display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1.5rem; margin-bottom: 1.5rem;">
                  ${mechanicsListEn.length > 0 ? `
                    <div style="background: rgba(17, 24, 39, 0.7); backdrop-filter: blur(12px); border: 1px solid rgba(255,255,255,0.08); border-radius: 1rem; padding: 1.5rem;">
                      <h2 id="lbl-mechanics-heading" style="font-size: 1.15rem; font-weight: 700; color: #ffffff; margin-top: 0; margin-bottom: 1rem; display: flex; align-items: center; gap: 0.5rem;">
                        <span>⚔️</span> <span id="lbl-mechanics-title">Key Mechanics &amp; Features</span>
                      </h2>
                      <ul id="mechanics-list" style="padding-left: 1.25rem; margin: 0;">${mechanicsLis}</ul>
                    </div>
                  ` : ''}
                  ${rewardsListEn.length > 0 ? `
                    <div style="background: rgba(17, 24, 39, 0.7); backdrop-filter: blur(12px); border: 1px solid rgba(255,255,255,0.08); border-radius: 1rem; padding: 1.5rem;">
                      <h2 id="lbl-rewards-heading" style="font-size: 1.15rem; font-weight: 700; color: #ffffff; margin-top: 0; margin-bottom: 1rem; display: flex; align-items: center; gap: 0.5rem;">
                        <span>🏆</span> <span id="lbl-rewards-title">Challenge Rewards</span>
                      </h2>
                      <ul id="rewards-list" style="padding-left: 1.25rem; margin: 0;">${rewardsLis}</ul>
                    </div>
                  ` : ''}
                </div>
              `;
            }

            const seasonSeo = SeoGenerator.generateSeoData({
              type: 'season',
              gameName,
              seasonName,
              description: seasonDesc,
              canonicalUrl: seasonCanonicalUrl,
              baseUrl: BASE_URL,
              startDate: start,
              endDate: end,
              developer: game.developer,
              lang: 'en'
            });

            let sPageHtml = seasonTemplate;
            sPageHtml = sPageHtml.replace(/{{GAME_ID}}/g, gameId);
            sPageHtml = sPageHtml.replace(/{{GAME_NAME}}/g, escapeHtml(gameName));
            sPageHtml = sPageHtml.replace(/{{SEASON_NAME}}/g, escapeHtml(seasonName));
            sPageHtml = sPageHtml.replace(/{{SEASON_TITLE}}/g, escapeHtml(seasonSeo.title));
            sPageHtml = sPageHtml.replace(/{{OG_LOCALE}}/g, seasonSeo.ogLocale);
            sPageHtml = sPageHtml.replace(/{{SEASON_SLUG}}/g, seasonSlug);
            sPageHtml = sPageHtml.replace(/{{SEASON_DESCRIPTION}}/g, escapeAttr(seasonSeo.description));
            sPageHtml = sPageHtml.replace(/{{BASE_URL}}/g, BASE_URL);
            sPageHtml = sPageHtml.replace(/{{CANONICAL_URL}}/g, escapeAttr(seasonCanonicalUrl));
            sPageHtml = sPageHtml.replace(/{{START_DATE}}/g, formattedStart);
            sPageHtml = sPageHtml.replace(/{{END_DATE}}/g, formattedEnd);
            sPageHtml = sPageHtml.replace(/{{DURATION}}/g, durationStr);
            sPageHtml = sPageHtml.replace(/{{STATUS_BADGE}}/g, statusBadge);
            sPageHtml = sPageHtml.replace(/{{SOURCE_LINK_HTML}}/g, linkHtml);
            sPageHtml = sPageHtml.replace(/{{PREV_SEASON_HTML}}/g, prevHtml);
            sPageHtml = sPageHtml.replace(/{{NEXT_SEASON_HTML}}/g, nextHtml);
            sPageHtml = sPageHtml.replace(/{{FAQ_HTML}}/g, faqHtml);
            sPageHtml = sPageHtml.replace(/{{SEASON_EXTRA_DETAILS_HTML}}/g, extraDetailsHtml);
            sPageHtml = sPageHtml.replace(/{{SEASON_DATA_JSON}}/g, escapeJsonForScript(JSON.stringify(item)));
            sPageHtml = sPageHtml.replace(/{{SCHEMA_JSONLD}}/g, escapeJsonForScript(JSON.stringify(seasonSchema, null, 2)));

            fs.writeFileSync(path.join(seasonTargetDir, 'index.html'), sPageHtml, 'utf-8');
          }
        }
        timelineHtml = rows.join('\n');
      } catch (err) {
        console.error(`[SSG] Error reading history for ${gameId}:`, err.message);
      }
    }

    // 2c. Load "Useful Links" array & "FAQ" array from content file if it exists
    let linksHtml = '';
    let linksJson = '[]';
    let faqList = [];
    let faqSectionHtml = '';
    let faqJson = '[]';
    if (fs.existsSync(contentPath)) {
      try {
        const contentData = JSON.parse(fs.readFileSync(contentPath, 'utf-8'));
        if (contentData.links && Array.isArray(contentData.links)) {
          linksJson = JSON.stringify(contentData.links);
          
          // Render links in English for static HTML
          const boxes = [];
          for (const item of contentData.links) {
            const category = escapeHtml(item.category || 'Official');
            const label = escapeHtml(item.label.en || '');
            const url = item.url || '#';
            
            boxes.push(`
              <div class="game-card__link-item">
                <span class="game-card__link-category">${category}</span>
                <a href="${escapeAttr(url)}" target="_blank" class="game-card__link-anchor">${label}</a>
              </div>
            `);
          }
          linksHtml = boxes.join('\n');
        }

        if (contentData.faq && Array.isArray(contentData.faq)) {
          faqList = contentData.faq;
          faqJson = JSON.stringify(contentData.faq);

          const faqBoxes = [];
          for (const item of contentData.faq) {
            const q = escapeHtml(item.question?.en || '');
            const a = escapeHtml(item.answer?.en || '');
            faqBoxes.push(`
              <div class="faq-item" style="background: rgba(15, 23, 42, 0.6); border: 1px solid rgba(255, 255, 255, 0.08); border-radius: 0.75rem; padding: 1rem 1.25rem;">
                <h3 class="faq-item__question" style="font-size: 0.95rem; font-weight: 700; color: #f3f4f6; margin-top: 0; margin-bottom: 0.5rem;">${q}</h3>
                <p class="faq-item__answer" style="font-size: 0.875rem; color: #9ca3af; line-height: 1.6; margin: 0;">${a}</p>
              </div>
            `);
          }
          faqSectionHtml = faqBoxes.join('\n');
        }
      } catch (err) {
        console.error(`[SSG] Error parsing content JSON for ${gameId}:`, err.message);
      }
    }

    // 3. Construct SEO values using SeoGenerator
    const canonicalUrl = `${BASE_URL}/games/${gameId}/`;
    
    // Construct dynamic description
    const currentSeasonName = game.currentSeason?.name?.en || 'TBA';
    const nextSeasonName = game.nextSeason?.name?.en || 'TBA';
    const nextSeasonStart = game.nextSeason?.startDate || '';
    
    let dynamicDesc = `Track ${gameName} season release dates. Current: ${currentSeasonName}. `;
    if (nextSeasonStart) {
      dynamicDesc += `Next season: ${nextSeasonName} starts on ${nextSeasonStart}. `;
    } else {
      dynamicDesc += `Next season: ${nextSeasonName} date TBA. `;
    }
    dynamicDesc += `Live countdown timer, next league start date, history timeline, and guides.`;

    const faqForSeo = faqList.map(item => ({
      question: item.question?.en || '',
      answer: item.answer?.en || ''
    }));

    const seoData = SeoGenerator.generateSeoData({
      type: 'game',
      gameName,
      description: dynamicDesc,
      canonicalUrl,
      baseUrl: BASE_URL,
      developer: game.developer,
      faq: faqForSeo,
      lang: 'en'
    });

    const schemaGraph = [];
    const gameNode = {
      "@type": "VideoGame",
      "name": gameName,
      "description": aboutHtml || `Detailed season information and countdown tracker for ${gameName}.`,
      "applicationCategory": "Game",
      "operatingSystem": "Windows",
      "publisher": {
        "@type": "Organization",
        "name": game.developer || "Unknown Developer"
      },
      "url": canonicalUrl
    };
    if (game.metadata) {
      if (game.metadata.platforms) {
        gameNode.gamePlatform = game.metadata.platforms;
      }
      if (game.metadata.tags) {
        gameNode.genre = game.metadata.tags;
      }
    }
    schemaGraph.push(gameNode);

    // Event for Current Season
    if (game.currentSeason?.startDate) {
      const curName = game.currentSeason.name?.en || 'TBA';
      schemaGraph.push({
        "@type": "Event",
        "name": `${gameName} - ${curName} Launch`,
        "startDate": game.currentSeason.startDate,
        ...(game.currentSeason.endDate ? { "endDate": game.currentSeason.endDate } : {}),
        "eventAttendanceMode": "https://schema.org/OnlineEventAttendanceMode",
        "eventStatus": "https://schema.org/EventScheduled",
        "location": {
          "@type": "VirtualLocation",
          "url": canonicalUrl
        },
        "description": `Launch event of the ${curName} season for ${gameName}.`,
        "organizer": {
          "@type": "Organization",
          "name": game.developer || "Unknown Developer"
        }
      });
    }

    // Event for Next Season
    if (game.nextSeason?.startDate) {
      const nxtName = game.nextSeason.name?.en || 'TBA';
      schemaGraph.push({
        "@type": "Event",
        "name": `${gameName} - ${nxtName} Launch`,
        "startDate": game.nextSeason.startDate,
        "eventAttendanceMode": "https://schema.org/OnlineEventAttendanceMode",
        "eventStatus": "https://schema.org/EventScheduled",
        "location": {
          "@type": "VirtualLocation",
          "url": canonicalUrl
        },
        "description": `Launch event of the upcoming ${nxtName} season for ${gameName}.`,
        "organizer": {
          "@type": "Organization",
          "name": game.developer || "Unknown Developer"
        }
      });
    }

    // FAQPage Schema
    if (faqForSeo.length > 0) {
      schemaGraph.push({
        "@type": "FAQPage",
        "mainEntity": faqForSeo.map(item => ({
          "@type": "Question",
          "name": item.question,
          "acceptedAnswer": {
            "@type": "Answer",
            "text": item.answer
          }
        }))
      });
    }

    const schemaObj = {
      "@context": "https://schema.org",
      "@graph": schemaGraph
    };
    const schemaJson = JSON.stringify(schemaObj, null, 2);

    // 4. Inject placeholders into layout
    let html = template;
    html = html.replace(/{{GAME_ID}}/g, gameId);
    html = html.replace(/{{GAME_NAME}}/g, escapeHtml(gameName));
    html = html.replace(/{{GAME_TITLE}}/g, escapeHtml(seoData.title));
    html = html.replace(/{{GAME_DESCRIPTION}}/g, escapeAttr(seoData.description));
    html = html.replace(/{{OG_LOCALE}}/g, seoData.ogLocale);
    html = html.replace(/{{BASE_URL}}/g, BASE_URL);
    html = html.replace(/{{GAME_COLOR}}/g, escapeAttr(gameColor));
    html = html.replace(/{{GAME_CARD_HTML}}/g, cardHtml);
    html = html.replace(/{{ABOUT_HTML}}/g, aboutHtml);
    html = html.replace(/{{ABOUT_JSON}}/g, escapeJsonForScript(aboutJson));
    html = html.replace(/{{CANONICAL_URL}}/g, escapeAttr(canonicalUrl));
    html = html.replace(/{{SCHEMA_JSONLD}}/g, escapeJsonForScript(schemaJson));
    html = html.replace(/{{TIMELINE_HTML}}/g, timelineHtml);
    html = html.replace(/{{TIMELINE_JSON}}/g, escapeJsonForScript(timelineJson));
    html = html.replace(/{{LINKS_HTML}}/g, linksHtml);
    html = html.replace(/{{LINKS_JSON}}/g, escapeJsonForScript(linksJson));
    html = html.replace(/{{FAQ_SECTION_HTML}}/g, faqSectionHtml);
    html = html.replace(/{{FAQ_JSON}}/g, escapeJsonForScript(faqJson));

    // 5. Write target index.html
    const targetDir = path.join(__dirname, `../games/${gameId}`);
    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }

    fs.writeFileSync(path.join(targetDir, 'index.html'), html, 'utf-8');
  }

  // 5.5 Generate changelog/index.html page
  const changelogTemplatePath = path.join(__dirname, '../src/templates/changelog.html');
  if (fs.existsSync(changelogTemplatePath)) {
    console.log('[SSG] Compiling ARPG Event Feed page (changelog)...');
    const changelogTemplate = fs.readFileSync(changelogTemplatePath, 'utf-8');
    const changelogList = database.changelog || [];

    const gameMetaMap = {
      'path-of-exile': { id: 'path-of-exile', name: 'Path of Exile 1', icon: 'skull', color: '#d97706' },
      'path-of-exile-2': { id: 'path-of-exile-2', name: 'Path of Exile 2', icon: 'sparkles', color: '#4b6e9c' },
      'diablo-iv': { id: 'diablo-iv', name: 'Diablo IV', icon: 'flame', color: '#b91c1c' },
      'last-epoch': { id: 'last-epoch', name: 'Last Epoch', icon: 'hourglass', color: '#8b5cf6' },
      'torchlight-infinite': { id: 'torchlight-infinite', name: 'Torchlight: Infinite', icon: 'zap', color: '#c27a2b' }
    };

    const changelogItemsHtml = changelogList.map((item, index) => {
      let dateStr = '';
      let anchorId = 'latest';
      if (item.timestamp) {
        const d = new Date(item.timestamp);
        dateStr = new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(d);
        const yyyy = d.getUTCFullYear();
        const mm = String(d.getUTCMonth() + 1).padStart(2, '0');
        const dd = String(d.getUTCDate()).padStart(2, '0');
        const hh = String(d.getUTCHours()).padStart(2, '0');
        const min = String(d.getUTCMinutes()).padStart(2, '0');
        anchorId = `update-${yyyy}-${mm}-${dd}-${hh}${min}`;
      }
      const itemKey = index === 0 ? 'latest' : anchorId;

      let gameId = item.gameId;
      const textEn = item.text?.en || item.text?.ru || '';
      const textRu = item.text?.ru || item.text?.en || '';
      const txtLower = textEn.toLowerCase();

      if (!gameId) {
        if (txtLower.includes('path of exile 2') || txtLower.includes('poe 2')) gameId = 'path-of-exile-2';
        else if (txtLower.includes('path of exile') || txtLower.includes('poe')) gameId = 'path-of-exile';
        else if (txtLower.includes('diablo')) gameId = 'diablo-iv';
        else if (txtLower.includes('last epoch')) gameId = 'last-epoch';
        else if (txtLower.includes('torchlight')) gameId = 'torchlight-infinite';
        else gameId = 'path-of-exile';
      }

      let type = item.type;
      if (!type) {
        if (txtLower.includes('launched') || txtLower.includes('запущен') || txtLower.includes('season launched')) type = 'launch';
        else if (txtLower.includes('exilecon') || txtLower.includes('announcement') || txtLower.includes('анонс') || txtLower.includes('showcase')) type = 'announcement';
        else type = 'article';
      }

      const meta = gameMetaMap[gameId] || gameMetaMap['path-of-exile'];
      const badgeLabelEn = type === 'launch' ? 'Season Launch' : (type === 'announcement' ? 'Announcement' : 'Article');

      const targetGame = (database.games || []).find(g => g.id === gameId);
      const sourceUrl = item.url || item.sourceUrl || targetGame?.currentSeason?.sourceUrl || targetGame?.website || '';

      return `
        <article id="${itemKey}" class="event-feed-card" data-game-id="${gameId}" data-event-type="${type}" data-timestamp="${item.timestamp || ''}" style="--game-accent-color: ${meta.color};">
          <div class="event-feed-card__header">
            <div class="event-feed-card__game-tag">
              <span class="event-feed-card__game-icon">${getIconSvg(meta.icon, { size: 14 })}</span>
              <span class="event-feed-card__game-name">${escapeHtml(meta.name)}</span>
            </div>
            <div class="event-feed-card__meta">
              <span class="feed-badge feed-badge--${type}">${badgeLabelEn}</span>
              <time class="event-feed-card__time" datetime="${item.timestamp || ''}">${dateStr}</time>
            </div>
          </div>
          <div class="event-feed-card__body">
            <div class="event-feed-card__text" data-lang="ru">${escapeHtml(textRu)}</div>
            <div class="event-feed-card__text" data-lang="en">${escapeHtml(textEn)}</div>
          </div>
          ${sourceUrl ? `
            <div class="event-feed-card__footer">
              <a href="${escapeAttr(sourceUrl)}" target="_blank" rel="noopener noreferrer" class="event-feed-card__link">
                <span class="event-feed-card__link-text">Read Original Source →</span>
              </a>
            </div>
          ` : ''}
        </article>
      `;
    }).join('\n');

    // Build sidebar upcoming launches widget
    const gamesList = database.games || [];
    const upcomingMiniCardsHtml = gamesList.map(g => {
      const gName = g.name?.en || g.id;
      const nextName = g.nextSeason?.name?.en || 'TBA';
      const nextDate = g.nextSeason?.startDate ? new Date(g.nextSeason.startDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }) : 'TBA';
      return `
        <div style="display: flex; align-items: center; justify-content: space-between; padding: 0.6rem 0; border-bottom: 1px solid rgba(255,255,255,0.05);">
          <div>
            <div style="font-size: 0.8rem; font-weight: 700; color: #f1f5f9;">${escapeHtml(gName)}</div>
            <div style="font-size: 0.72rem; color: #94a3b8; max-width: 170px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">${escapeHtml(nextName)}</div>
          </div>
          <div style="font-size: 0.75rem; font-weight: 700; color: #818cf8;">${escapeHtml(nextDate)}</div>
        </div>
      `;
    }).join('');

    const sidebarUpcomingWidget = `
      <section style="background: rgba(15, 23, 42, 0.65); backdrop-filter: blur(12px); border: 1px solid rgba(255, 255, 255, 0.08); border-radius: 12px; padding: 1.25rem;">
        <h3 style="font-family: var(--font-display); font-size: 0.8rem; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.75rem;">Upcoming Launches</h3>
        ${upcomingMiniCardsHtml}
      </section>
    `;

    const sidebarMobilePromo = `
      <section style="background: linear-gradient(135deg, rgba(99, 102, 241, 0.15), rgba(168, 85, 247, 0.1)); border: 1px solid rgba(99, 102, 241, 0.3); border-radius: 12px; padding: 1.25rem; text-align: center;">
        <h4 style="font-family: var(--font-display); font-size: 0.9rem; font-weight: 700; color: #f1f5f9; margin-bottom: 0.35rem;">SeasonForge Mobile</h4>
        <p style="font-size: 0.78rem; color: #94a3b8; line-height: 1.4; margin-bottom: 0.85rem;">Widgets &amp; season alerts for Android.</p>
        <a href="https://github.com/SeasonForge/seasonforge.github.io/releases" target="_blank" rel="noopener noreferrer" style="display: inline-block; background: #6366f1; color: #ffffff; text-decoration: none; font-size: 0.78rem; font-weight: 600; padding: 0.45rem 0.85rem; border-radius: 6px; transition: background 0.2s;">Download App</a>
      </section>
    `;

    let changelogHtml = changelogTemplate.replace(/{{CHANGELOG_ITEMS}}/g, changelogItemsHtml);
    changelogHtml = changelogHtml.replace(/{{SIDEBAR_UPCOMING_WIDGET}}/g, sidebarUpcomingWidget);
    changelogHtml = changelogHtml.replace(/{{SIDEBAR_MOBILE_PROMO}}/g, sidebarMobilePromo);
    changelogHtml = changelogHtml
      .replace(/<strong id="last-checked-time">[\s\S]*?<\/strong>/g, `<strong id="last-checked-time">${lastCheckedFormatted}</strong>`)
      .replace(/<strong id="last-updated-time">[\s\S]*?<\/strong>/g, `<strong id="last-updated-time">${lastUpdatedFormatted}</strong>`);

    const changelogDir = path.join(__dirname, '../changelog');
    if (!fs.existsSync(changelogDir)) {
      fs.mkdirSync(changelogDir, { recursive: true });
    }
    fs.writeFileSync(path.join(changelogDir, 'index.html'), changelogHtml, 'utf-8');
    console.log('[SSG] changelog/index.html generated successfully.');
  }

  // 5.6 Generate events/index.html page
  const eventsTemplatePath = path.join(__dirname, '../src/templates/events.html');
  const eventsDataPath = path.join(__dirname, '../data/events.json');

  if (fs.existsSync(eventsTemplatePath) && fs.existsSync(eventsDataPath)) {
    console.log('[SSG] Compiling ARPG Events & Drops page (events)...');
    const eventsTemplate = fs.readFileSync(eventsTemplatePath, 'utf-8');
    let eventsData = { events: [] };
    try {
      eventsData = JSON.parse(fs.readFileSync(eventsDataPath, 'utf-8'));
    } catch (e) {
      console.warn('[SSG] Failed reading events.json');
    }

    const rawEvents = Array.isArray(eventsData.events) ? eventsData.events : [];
    const now = new Date();

    const normalizedEvents = rawEvents.map(evt => {
      const nowMs = now.getTime();
      const startMs = new Date(evt.startDate).getTime();
      const endMs = evt.endDate ? new Date(evt.endDate).getTime() : null;

      let status = 'active';
      if (startMs > nowMs) status = 'upcoming';
      else if (endMs && nowMs > endMs) status = 'ended';

      return { ...evt, status };
    });

    const navbarHtml = renderNavbar(database.games || [], null, 'timeline', '../');
    const eventsContentHtml = renderEventsTimeline(normalizedEvents, database.games || [], { lang: 'en', basePath: '../' });

    let eventsHtml = eventsTemplate
      .replace(/{{NAVBAR}}/g, navbarHtml)
      .replace(/{{EVENTS_CONTENT}}/g, eventsContentHtml)
      .replace(/{{RAW_EVENTS_JSON}}/g, escapeJsonForScript(JSON.stringify(normalizedEvents)))
      .replace(/{{LAST_CHECKED_TIME}}/g, lastCheckedFormatted)
      .replace(/{{LAST_UPDATED_TIME}}/g, lastUpdatedFormatted);

    const eventsDir = path.join(__dirname, '../events');
    if (!fs.existsSync(eventsDir)) {
      fs.mkdirSync(eventsDir, { recursive: true });
    }
    fs.writeFileSync(path.join(eventsDir, 'index.html'), eventsHtml, 'utf-8');
    console.log('[SSG] events/index.html generated successfully.');
  }

  // 6. Generate sitemap.xml
  console.log('[SSG] Generating sitemap.xml...');
  const todayStr = new Date().toISOString().split('T')[0];
  let sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${BASE_URL}/</loc>
    <lastmod>${todayStr}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>${BASE_URL}/events/</loc>
    <lastmod>${todayStr}</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>${BASE_URL}/changelog/</loc>
    <lastmod>${todayStr}</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
  </url>
`;

  for (const game of games) {
    sitemapXml += `  <url>
    <loc>${BASE_URL}/games/${game.id}/</loc>
    <lastmod>${todayStr}</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
  </url>
`;
  }

  for (const seasonUrl of generatedSeasonUrls) {
    sitemapXml += `  <url>
    <loc>${escapeAttr(seasonUrl)}</loc>
    <lastmod>${todayStr}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
`;
  }

  sitemapXml += `  <url>
    <loc>${BASE_URL}/privacy/</loc>
    <lastmod>${todayStr}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
`;

  sitemapXml += `</urlset>\n`;
  fs.writeFileSync(path.join(__dirname, '../sitemap.xml'), sitemapXml, 'utf-8');
  console.log('[SSG] sitemap.xml written successfully.');

  // 7. Generate robots.txt
  console.log('[SSG] Generating robots.txt...');
  const robotsTxt = `User-agent: *
Allow: /

Sitemap: ${BASE_URL}/sitemap.xml
`;
  fs.writeFileSync(path.join(__dirname, '../robots.txt'), robotsTxt, 'utf-8');
  console.log('[SSG] robots.txt written successfully.');

  console.log(`=== SSG Complete: Generated detail pages for ${games.length} games ===`);

  // 8. Automated verification of all generated pages
  validateGeneratedPages(BASE_URL, games, generatedSeasonUrls);
}

function validateGeneratedPages(BASE_URL, games, generatedSeasonUrls) {
  validatePages(BASE_URL, games, generatedSeasonUrls, path.join(__dirname, '..'));
}

build().catch(error => {
  console.error('[SSG] Build process failed:', error);
  process.exit(1);
});
