import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import CleanCSS from 'clean-css';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const srcDir = path.join(__dirname, '../src');
const v2Dir = path.join(srcDir, 'styles/v2');
const distDir = path.join(v2Dir, 'dist');
const outputFile = path.join(distDir, 'v2-bundle.css');
const outputMinFile = path.join(distDir, 'v2-bundle.min.css');

// Ordered list of modules for predictable CSS cascade
const modulePaths = [
  path.join(v2Dir, 'tokens.css'),
  path.join(v2Dir, 'base.css'),
  path.join(v2Dir, 'layout.css'),
  path.join(v2Dir, 'hero-parallax.css'),
  path.join(v2Dir, 'header.css'),
  path.join(v2Dir, 'navbar.css'),
  path.join(v2Dir, 'cards.css'),
  path.join(srcDir, 'desktop/styles/cards-desktop.css'),
  path.join(srcDir, 'mobile/styles/cards-mobile.css'),
  path.join(v2Dir, 'timeline.css'),
  path.join(v2Dir, 'modals.css'),
  path.join(v2Dir, 'mobile-nav.css'),
  path.join(v2Dir, 'event-feed.css'),
  path.join(v2Dir, 'events.css'),
  path.join(srcDir, 'desktop/styles/events-desktop.css'),
  path.join(srcDir, 'mobile/styles/events-mobile.css'),
  path.join(v2Dir, 'donate.css'),
];

function buildV2() {
  console.log('=== Building SeasonForge CSS v2 Bundle ===');

  if (!fs.existsSync(v2Dir)) {
    console.error(`Source directory not found: ${v2Dir}`);
    process.exit(1);
  }

  if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir, { recursive: true });
  }

  let combinedCss = `/* SeasonForge CSS v2 Bundle — AUTO-GENERATED BY scripts/build-v2.js */\n/* Generated on: ${new Date().toISOString()} */\n\n`;
  let processedCount = 0;

  for (const filePath of modulePaths) {
    const fileName = path.basename(filePath);
    if (fs.existsSync(filePath)) {
      const content = fs.readFileSync(filePath, 'utf-8');
      combinedCss += `/* --- Module: ${fileName} (${path.relative(srcDir, filePath)}) --- */\n${content}\n\n`;
      processedCount++;
      console.log(`  [+] Included: ${path.relative(srcDir, filePath)}`);
    } else {
      console.warn(`  [-] Missing module: ${filePath}`);
    }
  }

  // Write dev bundle
  fs.writeFileSync(outputFile, combinedCss, 'utf-8');
  const devSize = (Buffer.byteLength(combinedCss) / 1024).toFixed(1);

  // Minify for production
  const minified = new CleanCSS({
    level: {
      1: { specialComments: 0 },
      2: { mergeMedia: true, restructureRules: true }
    }
  }).minify(combinedCss);

  if (minified.errors && minified.errors.length > 0) {
    console.error('CSS minification errors:', minified.errors);
  }

  fs.writeFileSync(outputMinFile, minified.styles, 'utf-8');
  const minSize = (Buffer.byteLength(minified.styles) / 1024).toFixed(1);
  const savings = ((1 - minified.styles.length / combinedCss.length) * 100).toFixed(0);

  console.log(`\nBundled ${processedCount} module(s):`);
  console.log(`  Dev:  ${outputFile} (${devSize} KB)`);
  console.log(`  Min:  ${outputMinFile} (${minSize} KB, −${savings}%)`);
}

export { buildV2 };

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  buildV2();
}

