import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const v2Dir = path.join(__dirname, '../src/styles/v2');
const distDir = path.join(v2Dir, 'dist');
const outputFile = path.join(distDir, 'v2-bundle.css');

// Ordered list of modules for predictable CSS cascade
const moduleOrder = [
  'tokens.css',
  'base.css',
  'layout.css',
  'hero-parallax.css',
  'header.css',
  'navbar.css',
  'cards.css',
  'timeline.css',
  'modals.css',
  'mobile-nav.css',
  'event-feed.css',
];

function buildV2() {
  console.log('=== Building SeasonForge CSS v2 Bundle ===');

  if (!fs.existsSync(v2Dir)) {
    console.error(`Source directory not found: ${v2Dir}`);
    process.exit(1);
  }

  if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir, { recursive: true });
  }

  let combinedCss = `/* SeasonForge CSS v2 Bundle — AUTO-GENERATED BY scripts/build-v2.js */\n/* Generated on: ${new Date().toISOString()} */\n\n`;
  let processedCount = 0;

  for (const fileName of moduleOrder) {
    const filePath = path.join(v2Dir, fileName);
    if (fs.existsSync(filePath)) {
      const content = fs.readFileSync(filePath, 'utf-8');
      combinedCss += `/* --- Module: ${fileName} --- */\n${content}\n\n`;
      processedCount++;
      console.log(`  [+] Included: ${fileName}`);
    } else {
      console.warn(`  [-] Missing module: ${fileName}`);
    }
  }

  fs.writeFileSync(outputFile, combinedCss, 'utf-8');
  console.log(`\nSuccessfully bundled ${processedCount} module(s) into: ${outputFile}`);
}

export { buildV2 };

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  buildV2();
}
